/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as PublicAuthRouteImport } from './routes/_public/_auth'
import { Route as PublicHeritageRouteImport } from './routes/_public/heritage'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as AdminGuardRouteImport } from './routes/admin/_guard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as PublicAuthCartRouteImport } from './routes/_public/_auth/cart'
import { Route as PublicAuthCheckoutRouteImport } from './routes/_public/_auth/checkout'
import { Route as PublicAuthProfileRouteImport } from './routes/_public/_auth/profile'
import { Route as PublicAuthWishlistRouteImport } from './routes/_public/_auth/wishlist'
import { Route as PublicCategorySlugRouteImport } from './routes/_public/category/$slug'
import { Route as PublicShopIndexRouteImport } from './routes/_public/shop/index'
import { Route as PublicShopSlugRouteImport } from './routes/_public/shop/$slug'
import { Route as AdminGuardIndexRouteImport } from './routes/admin/_guard/index'
import { Route as AdminGuardCustomersRouteImport } from './routes/admin/_guard/customers'
import { Route as AdminGuardDashboardRouteImport } from './routes/admin/_guard/dashboard'
import { Route as AdminGuardOrdersRouteImport } from './routes/admin/_guard/orders'
import { Route as AdminGuardProductsRouteImport } from './routes/admin/_guard/products'
import { Route as AdminGuardReviewsRouteImport } from './routes/admin/_guard/reviews'
import { Route as PublicAuthOrdersIndexRouteImport } from './routes/_public/_auth/orders/index'
import { Route as PublicAuthOrdersOrderNumberRouteImport } from './routes/_public/_auth/orders/$orderNumber'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHeritageRoute = PublicHeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const AdminGuardRoute = AdminGuardRouteImport.update({
  id: '/admin/_guard',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthCartRoute = PublicAuthCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthCheckoutRoute = PublicAuthCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthProfileRoute = PublicAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthWishlistRoute = PublicAuthWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicCategorySlugRoute = PublicCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShopIndexRoute = PublicShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShopSlugRoute = PublicShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminGuardIndexRoute = AdminGuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGuardRoute,
} as any)
const AdminGuardCustomersRoute = AdminGuardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminGuardRoute,
} as any)
const AdminGuardDashboardRoute = AdminGuardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminGuardRoute,
} as any)
const AdminGuardOrdersRoute = AdminGuardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminGuardRoute,
} as any)
const AdminGuardProductsRoute = AdminGuardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminGuardRoute,
} as any)
const AdminGuardReviewsRoute = AdminGuardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminGuardRoute,
} as any)
const PublicAuthOrdersIndexRoute = PublicAuthOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthOrdersOrderNumberRoute =
  PublicAuthOrdersOrderNumberRouteImport.update({
    id: '/orders/$orderNumber',
    path: '/orders/$orderNumber',
    getParentRoute: () => PublicAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/$': typeof PublicSplatRoute
  '/heritage': typeof PublicHeritageRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/admin': typeof AdminGuardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/cart': typeof PublicAuthCartRoute
  '/checkout': typeof PublicAuthCheckoutRoute
  '/profile': typeof PublicAuthProfileRoute
  '/wishlist': typeof PublicAuthWishlistRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/shop/$slug': typeof PublicShopSlugRoute
  '/admin/customers': typeof AdminGuardCustomersRoute
  '/admin/dashboard': typeof AdminGuardDashboardRoute
  '/admin/orders': typeof AdminGuardOrdersRoute
  '/admin/products': typeof AdminGuardProductsRoute
  '/admin/reviews': typeof AdminGuardReviewsRoute
  '/shop/': typeof PublicShopIndexRoute
  '/admin/': typeof AdminGuardIndexRoute
  '/orders/$orderNumber': typeof PublicAuthOrdersOrderNumberRoute
  '/orders/': typeof PublicAuthOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof PublicSplatRoute
  '/': typeof PublicIndexRoute
  '/heritage': typeof PublicHeritageRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/cart': typeof PublicAuthCartRoute
  '/checkout': typeof PublicAuthCheckoutRoute
  '/profile': typeof PublicAuthProfileRoute
  '/wishlist': typeof PublicAuthWishlistRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/shop/$slug': typeof PublicShopSlugRoute
  '/admin/customers': typeof AdminGuardCustomersRoute
  '/admin/dashboard': typeof AdminGuardDashboardRoute
  '/admin/orders': typeof AdminGuardOrdersRoute
  '/admin/products': typeof AdminGuardProductsRoute
  '/admin/reviews': typeof AdminGuardReviewsRoute
  '/shop': typeof PublicShopIndexRoute
  '/admin': typeof AdminGuardIndexRoute
  '/orders/$orderNumber': typeof PublicAuthOrdersOrderNumberRoute
  '/orders': typeof PublicAuthOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/$': typeof PublicSplatRoute
  '/_public/_auth': typeof PublicAuthRouteWithChildren
  '/_public/heritage': typeof PublicHeritageRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/admin/_guard': typeof AdminGuardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/_auth/cart': typeof PublicAuthCartRoute
  '/_public/_auth/checkout': typeof PublicAuthCheckoutRoute
  '/_public/_auth/profile': typeof PublicAuthProfileRoute
  '/_public/_auth/wishlist': typeof PublicAuthWishlistRoute
  '/_public/category/$slug': typeof PublicCategorySlugRoute
  '/_public/shop/$slug': typeof PublicShopSlugRoute
  '/admin/_guard/customers': typeof AdminGuardCustomersRoute
  '/admin/_guard/dashboard': typeof AdminGuardDashboardRoute
  '/admin/_guard/orders': typeof AdminGuardOrdersRoute
  '/admin/_guard/products': typeof AdminGuardProductsRoute
  '/admin/_guard/reviews': typeof AdminGuardReviewsRoute
  '/_public/shop/': typeof PublicShopIndexRoute
  '/admin/_guard/': typeof AdminGuardIndexRoute
  '/_public/_auth/orders/$orderNumber': typeof PublicAuthOrdersOrderNumberRoute
  '/_public/_auth/orders/': typeof PublicAuthOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/heritage'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/login'
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/wishlist'
    | '/category/$slug'
    | '/shop/$slug'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/shop/'
    | '/admin/'
    | '/orders/$orderNumber'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/heritage'
    | '/login'
    | '/register'
    | '/admin/login'
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/wishlist'
    | '/category/$slug'
    | '/shop/$slug'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/shop'
    | '/admin'
    | '/orders/$orderNumber'
    | '/orders'
  id:
    | '__root__'
    | '/_public'
    | '/_public/$'
    | '/_public/_auth'
    | '/_public/heritage'
    | '/_public/login'
    | '/_public/register'
    | '/admin/_guard'
    | '/admin/login'
    | '/_public/'
    | '/_public/_auth/cart'
    | '/_public/_auth/checkout'
    | '/_public/_auth/profile'
    | '/_public/_auth/wishlist'
    | '/_public/category/$slug'
    | '/_public/shop/$slug'
    | '/admin/_guard/customers'
    | '/admin/_guard/dashboard'
    | '/admin/_guard/orders'
    | '/admin/_guard/products'
    | '/admin/_guard/reviews'
    | '/_public/shop/'
    | '/admin/_guard/'
    | '/_public/_auth/orders/$orderNumber'
    | '/_public/_auth/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminGuardRoute: typeof AdminGuardRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/heritage': {
      id: '/_public/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof PublicHeritageRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/_guard': {
      id: '/admin/_guard'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/cart': {
      id: '/_public/_auth/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicAuthCartRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/checkout': {
      id: '/_public/_auth/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicAuthCheckoutRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/profile': {
      id: '/_public/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicAuthProfileRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/wishlist': {
      id: '/_public/_auth/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof PublicAuthWishlistRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/category/$slug': {
      id: '/_public/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof PublicCategorySlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shop/': {
      id: '/_public/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof PublicShopIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shop/$slug': {
      id: '/_public/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof PublicShopSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/_guard/': {
      id: '/admin/_guard/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminGuardIndexRouteImport
      parentRoute: typeof AdminGuardRoute
    }
    '/admin/_guard/customers': {
      id: '/admin/_guard/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminGuardCustomersRouteImport
      parentRoute: typeof AdminGuardRoute
    }
    '/admin/_guard/dashboard': {
      id: '/admin/_guard/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminGuardDashboardRouteImport
      parentRoute: typeof AdminGuardRoute
    }
    '/admin/_guard/orders': {
      id: '/admin/_guard/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminGuardOrdersRouteImport
      parentRoute: typeof AdminGuardRoute
    }
    '/admin/_guard/products': {
      id: '/admin/_guard/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminGuardProductsRouteImport
      parentRoute: typeof AdminGuardRoute
    }
    '/admin/_guard/reviews': {
      id: '/admin/_guard/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminGuardReviewsRouteImport
      parentRoute: typeof AdminGuardRoute
    }
    '/_public/_auth/orders/': {
      id: '/_public/_auth/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof PublicAuthOrdersIndexRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/orders/$orderNumber': {
      id: '/_public/_auth/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof PublicAuthOrdersOrderNumberRouteImport
      parentRoute: typeof PublicAuthRoute
    }
  }
}

interface PublicAuthRouteChildren {
  PublicAuthCartRoute: typeof PublicAuthCartRoute
  PublicAuthCheckoutRoute: typeof PublicAuthCheckoutRoute
  PublicAuthProfileRoute: typeof PublicAuthProfileRoute
  PublicAuthWishlistRoute: typeof PublicAuthWishlistRoute
  PublicAuthOrdersOrderNumberRoute: typeof PublicAuthOrdersOrderNumberRoute
  PublicAuthOrdersIndexRoute: typeof PublicAuthOrdersIndexRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthCartRoute: PublicAuthCartRoute,
  PublicAuthCheckoutRoute: PublicAuthCheckoutRoute,
  PublicAuthProfileRoute: PublicAuthProfileRoute,
  PublicAuthWishlistRoute: PublicAuthWishlistRoute,
  PublicAuthOrdersOrderNumberRoute: PublicAuthOrdersOrderNumberRoute,
  PublicAuthOrdersIndexRoute: PublicAuthOrdersIndexRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicHeritageRoute: typeof PublicHeritageRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCategorySlugRoute: typeof PublicCategorySlugRoute
  PublicShopSlugRoute: typeof PublicShopSlugRoute
  PublicShopIndexRoute: typeof PublicShopIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicHeritageRoute: PublicHeritageRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCategorySlugRoute: PublicCategorySlugRoute,
  PublicShopSlugRoute: PublicShopSlugRoute,
  PublicShopIndexRoute: PublicShopIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminGuardRouteChildren {
  AdminGuardCustomersRoute: typeof AdminGuardCustomersRoute
  AdminGuardDashboardRoute: typeof AdminGuardDashboardRoute
  AdminGuardOrdersRoute: typeof AdminGuardOrdersRoute
  AdminGuardProductsRoute: typeof AdminGuardProductsRoute
  AdminGuardReviewsRoute: typeof AdminGuardReviewsRoute
  AdminGuardIndexRoute: typeof AdminGuardIndexRoute
}

const AdminGuardRouteChildren: AdminGuardRouteChildren = {
  AdminGuardCustomersRoute: AdminGuardCustomersRoute,
  AdminGuardDashboardRoute: AdminGuardDashboardRoute,
  AdminGuardOrdersRoute: AdminGuardOrdersRoute,
  AdminGuardProductsRoute: AdminGuardProductsRoute,
  AdminGuardReviewsRoute: AdminGuardReviewsRoute,
  AdminGuardIndexRoute: AdminGuardIndexRoute,
}

const AdminGuardRouteWithChildren = AdminGuardRoute._addFileChildren(
  AdminGuardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminGuardRoute: AdminGuardRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
